
/* Code automatically generated by Vult https://github.com/modlfo/vult */
#include "Cymbal.h"

void Cymbal__ctx_type_15_init(Cymbal__ctx_type_15 &_output_){
   Cymbal__ctx_type_15 _ctx;
   _ctx.rate = 0.0f;
   _ctx.phase = 0.0f;
   Cymbal__ctx_type_0_init(_ctx._inst366);
   Cymbal__ctx_type_1_init(_ctx._inst19e);
   _output_ = _ctx;
   return ;
}

float Cymbal_phase(Cymbal__ctx_type_15 &_ctx, float cv, float reset){
   if(Cymbal_change(_ctx._inst19e,cv)){
      _ctx.rate = Cymbal_cvToRate_1024(cv);
   }
   if(Cymbal_edge(_ctx._inst366,(reset > 0.5f))){
      _ctx.phase = 0.0f;
   }
   else
   {
      _ctx.phase = (_ctx.phase + _ctx.rate);
   }
   if(_ctx.phase > 1024.f){
      _ctx.phase = (-1024.f + _ctx.phase);
   }
   return (0.0009765625f * _ctx.phase);
}

void Cymbal__ctx_type_16_init(Cymbal__ctx_type_16 &_output_){
   Cymbal__ctx_type_16 _ctx;
   _ctx.trig = false;
   Cymbal__ctx_type_15_init(_ctx.p);
   Cymbal__ctx_type_0_init(_ctx._inst166);
   _output_ = _ctx;
   return ;
}

float Cymbal_sine(Cymbal__ctx_type_16 &_ctx, float cv, float reset){
   if(Cymbal_edge(_ctx._inst166,(reset > 0.5f))){
      _ctx.trig = true;
   }
   float phase;
   phase = Cymbal_phase(_ctx.p,cv,0.0f);
   if((phase < 1e-018f) && _ctx.trig){
      _ctx.trig = false;
      Cymbal_phase(_ctx.p,cv,0.0f);
   }
   return Cymbal_nsine(phase);
}

void Cymbal__ctx_type_17_init(Cymbal__ctx_type_17 &_output_){
   Cymbal__ctx_type_17 _ctx;
   _ctx.target = 0.0f;
   _ctx.state = 0;
   _ctx.rate = 0.0f;
   _ctx.out = 0.0f;
   _ctx.hold_phase = 0.0f;
   _ctx.ahr_ret_1 = 0.0f;
   _ctx.ahr_ret_0 = 0.0f;
   Cymbal__ctx_type_0_init(_ctx._inst366);
   Cymbal__ctx_type_0_init(_ctx._inst166);
   _output_ = _ctx;
   return ;
}

void Cymbal_ahr(Cymbal__ctx_type_17 &_ctx, float gate, float a, float h, float r){
   int release;
   release = 0;
   int attack;
   attack = 1;
   int hold;
   hold = 2;
   int reset;
   reset = 3;
   uint8_t bgate;
   bgate = (gate > 0.0f);
   if(Cymbal_edge(_ctx._inst166,bgate)){
      _ctx.state = reset;
   }
   float resetting;
   if(_ctx.state == reset){
      resetting = 1.f;
   }
   else
   {
      resetting = 0.0f;
   }
   if(Cymbal_edge(_ctx._inst366,(_ctx.out > 1024.f))){
      _ctx.hold_phase = 0.0f;
      _ctx.state = hold;
   }
   if((_ctx.out < 10.f) && (_ctx.state == reset)){
      _ctx.state = attack;
   }
   if((_ctx.hold_phase > 100.f) && (_ctx.state == hold)){
      _ctx.state = release;
   }
   if(_ctx.state == reset){
      _ctx.rate = 0.990099009901f;
      _ctx.target = 0.0f;
   }
   if(_ctx.state == attack){
      _ctx.rate = (1.f / (0.01f + (100.f * a)));
      _ctx.target = 1228.8f;
   }
   if(_ctx.state == hold){
      float hrate;
      hrate = (1.f / (0.01f + (100.f * h)));
      _ctx.hold_phase = (_ctx.hold_phase + hrate);
   }
   if(_ctx.state == release){
      _ctx.rate = (1.f / (0.01f + (100.f * r)));
      _ctx.target = 0.0f;
   }
   _ctx.out = (_ctx.out + (0.005f * _ctx.rate * (_ctx.target + (- _ctx.out))));
   _ctx.ahr_ret_0 = float_clip((0.0009765625f * _ctx.out),0.0f,1.f);
   _ctx.ahr_ret_1 = resetting;
   return ;
}

float Cymbal_pinker(Cymbal__ctx_type_18 &_ctx, float x){
   float b0;
   b0 = 0.0277129863191f;
   float b1;
   b1 = 0.0277129863191f;
   float a1;
   a1 = -0.944574027362f;
   float w0;
   w0 = (x + (- (_ctx.w1 * a1)));
   float y0;
   y0 = ((_ctx.w1 * b1) + (b0 * w0));
   _ctx.w1 = w0;
   return y0;
}

void Cymbal__ctx_type_19_init(Cymbal__ctx_type_19 &_output_){
   Cymbal__ctx_type_19 _ctx;
   _ctx.x2 = 0;
   _ctx.x1 = 0;
   Cymbal__ctx_type_18_init(_ctx._inst115);
   _output_ = _ctx;
   return ;
}

float Cymbal_noise(Cymbal__ctx_type_19 &_ctx, float color){
   _ctx.x1 = ((7919 + (17389 * _ctx.x1)) % 32768);
   float y1;
   y1 = (3.0517578125e-005f * int_to_float(_ctx.x1));
   _ctx.x2 = ((12553 + (27449 * _ctx.x2)) % 32768);
   float y2;
   y2 = (3.0517578125e-005f * int_to_float(_ctx.x2));
   float out;
   if(color > 0.5f){
      out = Cymbal_pinker(_ctx._inst115,(y1 + (- y2)));
   }
   else
   {
      out = (y1 + (- y2));
   }
   return (0.5f * out);
}

void Cymbal__ctx_type_20_init(Cymbal__ctx_type_20 &_output_){
   Cymbal__ctx_type_20 _ctx;
   Cymbal__ctx_type_19_init(_ctx._inst364);
   Cymbal__ctx_type_16_init(_ctx._inst232);
   Cymbal__ctx_type_17_init(_ctx._inst12);
   _output_ = _ctx;
   return ;
}

float Cymbal_process(Cymbal__ctx_type_20 &_ctx, float gate, float decay, float pitch){
   float osc_env;
   float env_reset;
   Cymbal_ahr(_ctx._inst12,gate,0.001f,(0.001f + decay),(0.001f + decay));
   osc_env = Cymbal_ahr_ret_0(_ctx._inst12);
   env_reset = Cymbal_ahr_ret_1(_ctx._inst12);
   float osc;
   osc = Cymbal_sine(_ctx._inst232,pitch,env_reset);
   float noise;
   noise = Cymbal_noise(_ctx._inst364,osc);
   return (noise * osc_env);
}


