
/* Code automatically generated by Vult https://github.com/modlfo/vult */
#include "Phasedist.h"

void Phasedist__ctx_type_16_init(Phasedist__ctx_type_16 &_output_){
   Phasedist__ctx_type_16 _ctx;
   _ctx.rate = 0.0f;
   _ctx.phase = 0.0f;
   Phasedist__ctx_type_4_init(_ctx._inst3cb);
   Phasedist__ctx_type_5_init(_ctx._inst11a);
   _output_ = _ctx;
   return ;
}

float Phasedist_phase(Phasedist__ctx_type_16 &_ctx, float cv, float reset){
   if(Phasedist_change(_ctx._inst11a,cv)){
      _ctx.rate = Phasedist_cvToRate_1024(cv);
   }
   if(Phasedist_edge(_ctx._inst3cb,(reset > 0.5f))){
      _ctx.phase = 0.0f;
   }
   else
   {
      _ctx.phase = (_ctx.phase + _ctx.rate);
   }
   if(_ctx.phase > 1024.f){
      _ctx.phase = (-1024.f + _ctx.phase);
   }
   return (0.0009765625f * _ctx.phase);
}

void Phasedist__ctx_type_17_init(Phasedist__ctx_type_17 &_output_){
   Phasedist__ctx_type_17 _ctx;
   _ctx.pre_phase1 = 0.0f;
   Phasedist__ctx_type_16_init(_ctx._inst364);
   Phasedist__ctx_type_6_init(_ctx._inst2b6);
   Phasedist__ctx_type_16_init(_ctx._inst164);
   _output_ = _ctx;
   return ;
}

float Phasedist_process(Phasedist__ctx_type_17 &_ctx, float cv, float detune){
   float phase1;
   phase1 = Phasedist_phase(_ctx._inst164,cv,0.0f);
   float comp;
   comp = (1.f + (- phase1));
   float reset;
   reset = (_ctx.pre_phase1 + (- phase1));
   _ctx.pre_phase1 = phase1;
   float phase2;
   phase2 = Phasedist_phase(_ctx._inst364,(cv + Phasedist_smooth(_ctx._inst2b6,(0.5f * detune))),reset);
   float sine;
   sine = Phasedist_nsine(phase2);
   return (comp * sine);
}


