
/* Code automatically generated by Vult https://github.com/modlfo/vult */
#ifndef PHASEDIST_H
#define PHASEDIST_H
#include <stdint.h>
#include <math.h>
#include "vultin.h"
#include "Phasedist.tables.h"

static_inline float Phasedist_nsine_raw_c0(int index){
   return Phasedist_nsine_c0[index];
};

static_inline float Phasedist_nsine_raw_c1(int index){
   return Phasedist_nsine_c1[index];
};

static_inline float Phasedist_nsine_raw_c2(int index){
   return Phasedist_nsine_c2[index];
};

static_inline float Phasedist_nsine(float x){
   int index;
   index = int_clip(float_to_int((127.f * x)),0,127);
   return (float_wrap_array(Phasedist_nsine_c0)[index] + (x * (float_wrap_array(Phasedist_nsine_c1)[index] + (x * float_wrap_array(Phasedist_nsine_c2)[index]))));
}

typedef struct Phasedist__ctx_type_4 {
   uint8_t pre;
} Phasedist__ctx_type_4;

typedef Phasedist__ctx_type_4 Phasedist_edge_type;

static_inline void Phasedist__ctx_type_4_init(Phasedist__ctx_type_4 &_output_){
   Phasedist__ctx_type_4 _ctx;
   _ctx.pre = false;
   _output_ = _ctx;
   return ;
}

static_inline void Phasedist_edge_init(Phasedist__ctx_type_4 &_output_){
   Phasedist__ctx_type_4_init(_output_);
   return ;
}

static_inline uint8_t Phasedist_edge(Phasedist__ctx_type_4 &_ctx, uint8_t x){
   uint8_t ret;
   ret = (x && bool_not(_ctx.pre));
   _ctx.pre = x;
   return ret;
}

typedef struct Phasedist__ctx_type_5 {
   float pre_x;
} Phasedist__ctx_type_5;

typedef Phasedist__ctx_type_5 Phasedist_change_type;

static_inline void Phasedist__ctx_type_5_init(Phasedist__ctx_type_5 &_output_){
   Phasedist__ctx_type_5 _ctx;
   _ctx.pre_x = 0.0f;
   _output_ = _ctx;
   return ;
}

static_inline void Phasedist_change_init(Phasedist__ctx_type_5 &_output_){
   Phasedist__ctx_type_5_init(_output_);
   return ;
}

static_inline uint8_t Phasedist_change(Phasedist__ctx_type_5 &_ctx, float x){
   uint8_t v;
   v = (_ctx.pre_x != x);
   _ctx.pre_x = x;
   return v;
}

typedef struct Phasedist__ctx_type_6 {
   float x;
} Phasedist__ctx_type_6;

typedef Phasedist__ctx_type_6 Phasedist_smooth_type;

static_inline void Phasedist__ctx_type_6_init(Phasedist__ctx_type_6 &_output_){
   Phasedist__ctx_type_6 _ctx;
   _ctx.x = 0.0f;
   _output_ = _ctx;
   return ;
}

static_inline void Phasedist_smooth_init(Phasedist__ctx_type_6 &_output_){
   Phasedist__ctx_type_6_init(_output_);
   return ;
}

static_inline float Phasedist_smooth(Phasedist__ctx_type_6 &_ctx, float input){
   _ctx.x = (_ctx.x + (0.005f * (input + (- _ctx.x))));
   return _ctx.x;
}

static_inline float Phasedist_pitchToRate_1024_raw_c0(int index){
   return Phasedist_pitchToRate_1024_c0[index];
};

static_inline float Phasedist_pitchToRate_1024_raw_c1(int index){
   return Phasedist_pitchToRate_1024_c1[index];
};

static_inline float Phasedist_pitchToRate_1024_raw_c2(int index){
   return Phasedist_pitchToRate_1024_c2[index];
};

static_inline float Phasedist_pitchToRate_1024(float pitch){
   int index;
   index = int_clip(float_to_int((0.244094488189f * pitch)),0,31);
   return (float_wrap_array(Phasedist_pitchToRate_1024_c0)[index] + (pitch * (float_wrap_array(Phasedist_pitchToRate_1024_c1)[index] + (pitch * float_wrap_array(Phasedist_pitchToRate_1024_c2)[index]))));
}

static_inline float Phasedist_cvToPitch(float cv){
   return (24.f + (120.f * cv));
};

static_inline float Phasedist_cvToRate_1024_raw_c0(int index){
   return Phasedist_cvToRate_1024_c0[index];
};

static_inline float Phasedist_cvToRate_1024_raw_c1(int index){
   return Phasedist_cvToRate_1024_c1[index];
};

static_inline float Phasedist_cvToRate_1024_raw_c2(int index){
   return Phasedist_cvToRate_1024_c2[index];
};

static_inline float Phasedist_cvToRate_1024(float cv){
   int index;
   index = int_clip(float_to_int((34.4444444444f * cv)),0,31);
   return (float_wrap_array(Phasedist_cvToRate_1024_c0)[index] + (cv * (float_wrap_array(Phasedist_cvToRate_1024_c1)[index] + (cv * float_wrap_array(Phasedist_cvToRate_1024_c2)[index]))));
}

typedef struct Phasedist__ctx_type_16 {
   float rate;
   float phase;
   Phasedist__ctx_type_4 _inst3cb;
   Phasedist__ctx_type_5 _inst11a;
} Phasedist__ctx_type_16;

typedef Phasedist__ctx_type_16 Phasedist_phase_type;

void Phasedist__ctx_type_16_init(Phasedist__ctx_type_16 &_output_);

static_inline void Phasedist_phase_init(Phasedist__ctx_type_16 &_output_){
   Phasedist__ctx_type_16_init(_output_);
   return ;
}

float Phasedist_phase(Phasedist__ctx_type_16 &_ctx, float cv, float reset);

typedef struct Phasedist__ctx_type_17 {
   float pre_phase1;
   Phasedist__ctx_type_16 _inst364;
   Phasedist__ctx_type_6 _inst2b6;
   Phasedist__ctx_type_16 _inst164;
} Phasedist__ctx_type_17;

typedef Phasedist__ctx_type_17 Phasedist_process_type;

void Phasedist__ctx_type_17_init(Phasedist__ctx_type_17 &_output_);

static_inline void Phasedist_process_init(Phasedist__ctx_type_17 &_output_){
   Phasedist__ctx_type_17_init(_output_);
   return ;
}

float Phasedist_process(Phasedist__ctx_type_17 &_ctx, float cv, float detune);



#endif // PHASEDIST_H
